### ISSUE TITLE
DBC 9.0.X

### ISSUE THREAD

**Issue by gbmv33** [TrinityCore/WoWDatabaseEditor#6]
Can update to support the 9.0.X Version?

**Comment by BAndysc** [comment]
Hello, I would like to, but sadly it is a bit more work, because currently used library to open DBC files (WDBXEditor) doesn't support 9.X format and the library has to be changed to something else that will support it. It is on my todo list, but can't say when I will do it.

However, any help with coding is appreciated and I would definitely assist with coding.

**Comment by quassia** [comment]
Any news regarding this? 
Thank you.

**Comment by BAndysc** [comment]
Hi, eventually this thing landed pretty far away on my "to do list", so low chance of doing it on my side, but if there is anyone willing to contribute, I am willing to help and explain where to add the support to it.

**Comment by quassia** [comment]
I was thinking it helps a lot now with the availability of TC Retail sniffers. 
People like myself who don't know too much coding can at least help with populating the world. And this tool (even without the SL DBC feature) is very useful.
Thank you :)

**Comment by BAndysc** [comment]
SL DBC is now supported thanks to funjoker contribution :)
